### ISSUE TITLE
Include dc parameter

### ISSUE THREAD

**Issue by marzlarz** [tolitius/envoy#8]
Would it be possible to include the "**dc**" parameter so that queries can be directed to a certain data center? 

Parameter Info:

> **dc** (string: "") - Specifies the datacenter to query. This will default to the datacenter of the agent being queried. This is specified as part of the URL as a query parameter.

**Example**:  _?dc=_

`# curl https://private-anon-892593d3f8-consul.apiary-mock.com/v1/kv/key?dc=&token=&flags=&cas=&acquire=&release=`

This is useful for a Consul setup that has a master data center that is being replicated out to other data centers. Writes need to occur in the master data center so that they are replicated out properly.

**Comment by tolitius** [comment]
all [KV Store Endpoints](https://www.consul.io/api/kv.html#parameters) params are supported through an optional map of parameters all envoy's commands take.

However looking at it again, I can see how it is not really obvious from the current docs.

I updated the docs to include a [better explanation](https://github.com/tolitius/envoy/blob/master/README.md#options) with an example with multiple params.

Thank you for bringing it up.

**Comment by marzlarz** [comment]
Thanks for the update. Closing this issue
